# basic options
title: Peace Paws Petsitting
author: Adam and Lianne
email: PeacePaws@AdamAndLianne.com
description: Peace of Mind for Your Own Pause
twitter_username: 
github_username:  AdamAndLianne

# Build settings
markdown: kramdown
theme: minima
